import jsPDF from "jspdf";

export const MEMA_COLORS = {
  accent: "#14b8a6",
  dark: "#0a1628",
  text: "#1e293b",
  lightGray: "#f1f5f9",
  white: "#ffffff",
};

/**
 * `organisationName` and `dateFormat` come from the requesting workspace's
 * settings JSONB (lib/workspace/settings.ts), resolved once in
 * app/api/export/pdf/route.ts and threaded through every generate*PDF call -
 * see that route's `organisationName`/`dateFormat` locals. Both are optional
 * so every existing caller (and every anonymous/no-settings workspace) keeps
 * today's generic output.
 */
export function addHeader(
  doc: jsPDF,
  title: string,
  organisationName?: string | null,
  dateFormat: "en-GB" | "iso" = "en-GB"
): number {
  // Accent bar
  doc.setFillColor(MEMA_COLORS.accent);
  doc.rect(20, 15, 40, 10, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("MEMA", 25, 22);

  // Title
  doc.setTextColor(MEMA_COLORS.text);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(title, 20, 40);

  // Subtitle: the workspace's organisation name, when set, replaces the
  // generic "Generated by..." line so a pack visibly identifies who it was
  // prepared for; otherwise the original generic subtitle is kept unchanged.
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  const subtitle = organisationName ? `Prepared for ${organisationName}` : "Generated by MEMA FinCrime Control Lab";
  doc.text(subtitle, 20, 47);
  const today = new Date();
  const dateLabel =
    dateFormat === "iso"
      ? today.toISOString().slice(0, 10)
      : today.toLocaleDateString("en-GB");
  doc.text(`Date: ${dateLabel}`, 20, 52);

  // Divider
  doc.setDrawColor(MEMA_COLORS.accent);
  doc.setLineWidth(0.5);
  doc.line(20, 57, 190, 57);

  return 64;
}

export function addFooter(doc: jsPDF, pageNumber: number, totalPages: number) {
  const h = doc.internal.pageSize.height;

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(20, h - 20, 190, h - 20);

  doc.setFontSize(7);
  doc.setTextColor(100, 100, 100);
  doc.text("MEMA Consultants Ltd | fincrime.memaconsultants.com", 20, h - 15);
  doc.text("Sources: FATF, Wolfsberg, FCA, JMLSG", 20, h - 11);

  doc.text(`Page ${pageNumber} of ${totalPages}`, 190, h - 11, { align: "right" });

  doc.setTextColor(MEMA_COLORS.accent);
  doc.text("memaconsultants.com", 190, h - 15, { align: "right" });
}

export function addFootersToAll(doc: jsPDF) {
  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    addFooter(doc, i, total);
  }
}

/**
 * Renders an evidence item's file column: "report.pdf (1.2MB)" when a file
 * is attached, "-" otherwise. Shared by every pack that lists evidence
 * (test/incident/readiness/reg-response/change) so "we hold the document"
 * vs "we linked to it" reads identically everywhere - a material
 * distinction per the Phase 7 brief, since a link can rot but an attached
 * file cannot.
 */
export function formatEvidenceFileCell(fileName: string | null | undefined, fileSizeBytes: number | null | undefined): string {
  if (!fileName) return "-";
  if (typeof fileSizeBytes !== "number" || !Number.isFinite(fileSizeBytes)) return fileName;
  const mb = fileSizeBytes / (1024 * 1024);
  const sizeLabel = mb >= 1 ? `${mb.toFixed(1)}MB` : `${Math.max(1, Math.round(fileSizeBytes / 1024))}KB`;
  return `${fileName} (${sizeLabel})`;
}

export function checkPageBreak(doc: jsPDF, yPos: number, needed = 40): number {
  if (yPos > doc.internal.pageSize.height - needed) {
    doc.addPage();
    return 20;
  }
  return yPos;
}
