import jsPDF from "jspdf";

export const MEMA_COLORS = {
  accent: "#14b8a6",
  dark: "#0a1628",
  text: "#1e293b",
  lightGray: "#f1f5f9",
  white: "#ffffff",
};

export function addHeader(doc: jsPDF, title: string): number {
  // Accent bar
  doc.setFillColor(MEMA_COLORS.accent);
  doc.rect(20, 15, 40, 10, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("MEMA", 25, 22);

  // Title
  doc.setTextColor(MEMA_COLORS.text);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(title, 20, 40);

  // Subtitle
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text("Generated by MEMA FinCrime Control Lab", 20, 47);
  doc.text(`Date: ${new Date().toLocaleDateString("en-GB")}`, 20, 52);

  // Divider
  doc.setDrawColor(MEMA_COLORS.accent);
  doc.setLineWidth(0.5);
  doc.line(20, 57, 190, 57);

  return 64;
}

export function addFooter(doc: jsPDF, pageNumber: number, totalPages: number) {
  const h = doc.internal.pageSize.height;

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(20, h - 20, 190, h - 20);

  doc.setFontSize(7);
  doc.setTextColor(100, 100, 100);
  doc.text("MEMA Consultants Ltd | fincrime.memaconsultants.com", 20, h - 15);
  doc.text("Sources: FATF, Wolfsberg, FCA, JMLSG", 20, h - 11);

  doc.text(`Page ${pageNumber} of ${totalPages}`, 190, h - 11, { align: "right" });

  doc.setTextColor(MEMA_COLORS.accent);
  doc.text("memaconsultants.com", 190, h - 15, { align: "right" });
}

export function addFootersToAll(doc: jsPDF) {
  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    addFooter(doc, i, total);
  }
}

export function checkPageBreak(doc: jsPDF, yPos: number, needed = 40): number {
  if (yPos > doc.internal.pageSize.height - needed) {
    doc.addPage();
    return 20;
  }
  return yPos;
}
