import type { RiskTheme, FirmType } from "../typologies/types";

/**
 * A real regulatory enforcement case, sourced from the FCA fines dataset
 * (regactions / fcafines). Every record carries a `sourceUrl` to the primary
 * notice. Generated by `scripts/build-enforcement-data.mjs` — do not hand-edit
 * the generated files; re-run the script to refresh.
 */
export interface EnforcementCase {
  firm: string;
  regulator: string; // e.g. "FCA"
  year: number;
  fine: string; // formatted, e.g. "£264.8m"
  amountGbp: number; // raw amount for sorting/aggregation
  breachType: string | null;
  breachCategories: string[];
  riskThemes: RiskTheme[];
  firmTypes: FirmType[]; // applicable firm types (empty if not classified)
  summary: string;
  sourceUrl: string | null;
}

export interface EnforcementBenchmarks {
  generatedAt: string; // ISO date the data was pulled
  source: string;
  totalCases: number;
  byRiskTheme: { theme: RiskTheme; count: number }[];
  byYear: { year: number; count: number; totalGbp: number }[];
  byFirmCategory: { category: string; count: number }[];
  topBreachCategories: { category: string; count: number }[];
  fineStats: {
    totalGbp: number;
    medianGbp: number;
    maxGbp: number;
    maxFirm: string;
  };
}
